// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type BlockType uint32

const (
	BlockTypeInvalid BlockType = 0
	BlockTypeDense   BlockType = 1
	BlockTypeSparse  BlockType = 2
)

var EnumNamesBlockType = map[BlockType]string{
	BlockTypeInvalid: "Invalid",
	BlockTypeDense:   "Dense",
	BlockTypeSparse:  "Sparse",
}

var EnumValuesBlockType = map[string]BlockType{
	"Invalid": BlockTypeInvalid,
	"Dense":   BlockTypeDense,
	"Sparse":  BlockTypeSparse,
}

func (v BlockType) String() string {
	if s, ok := EnumNamesBlockType[v]; ok {
		return s
	}
	return "BlockType(" + strconv.FormatInt(int64(v), 10) + ")"
}
