// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DenseLocations struct {
	_tab flatbuffers.Table
}

func GetRootAsDenseLocations(buf []byte, offset flatbuffers.UOffsetT) *DenseLocations {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DenseLocations{}
	x.Init(buf, n+offset)
	return x
}

func FinishDenseLocationsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDenseLocations(buf []byte, offset flatbuffers.UOffsetT) *DenseLocations {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DenseLocations{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDenseLocationsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DenseLocations) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DenseLocations) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DenseLocations) Locations(obj *Location, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 8
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DenseLocations) LocationsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func DenseLocationsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DenseLocationsAddLocations(builder *flatbuffers.Builder, locations flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(locations), 0)
}
func DenseLocationsStartLocationsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 4)
}
func DenseLocationsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
