// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FileHeader struct {
	_tab flatbuffers.Struct
}

func (rcv *FileHeader) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FileHeader) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *FileHeader) Signature() HeaderSignature {
	return HeaderSignature(rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(0)))
}
func (rcv *FileHeader) MutateSignature(n HeaderSignature) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(0), uint64(n))
}

func (rcv *FileHeader) Version() HeaderVersion {
	return HeaderVersion(rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(8)))
}
func (rcv *FileHeader) MutateVersion(n HeaderVersion) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(8), uint64(n))
}

func (rcv *FileHeader) DataOffset() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(16))
}
func (rcv *FileHeader) MutateDataOffset(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(16), n)
}

func (rcv *FileHeader) DataSize() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(24))
}
func (rcv *FileHeader) MutateDataSize(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(24), n)
}

func (rcv *FileHeader) IndexOffset() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(32))
}
func (rcv *FileHeader) MutateIndexOffset(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(32), n)
}

func (rcv *FileHeader) IndexSize() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(40))
}
func (rcv *FileHeader) MutateIndexSize(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(40), n)
}

func (rcv *FileHeader) MetadataOffset() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(48))
}
func (rcv *FileHeader) MutateMetadataOffset(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(48), n)
}

func (rcv *FileHeader) MetadataSize() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(56))
}
func (rcv *FileHeader) MutateMetadataSize(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(56), n)
}

func (rcv *FileHeader) ExtendedOffset() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(64))
}
func (rcv *FileHeader) MutateExtendedOffset(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(64), n)
}

func (rcv *FileHeader) ExtendedSize() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(72))
}
func (rcv *FileHeader) MutateExtendedSize(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(72), n)
}

func (rcv *FileHeader) Reserved1() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(80))
}
func (rcv *FileHeader) MutateReserved1(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(80), n)
}

func (rcv *FileHeader) Reserved2() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(88))
}
func (rcv *FileHeader) MutateReserved2(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(88), n)
}

func CreateFileHeader(builder *flatbuffers.Builder, signature HeaderSignature, version HeaderVersion, dataOffset uint64, dataSize uint64, indexOffset uint64, indexSize uint64, metadataOffset uint64, metadataSize uint64, extendedOffset uint64, extendedSize uint64, reserved1 uint64, reserved2 uint64) flatbuffers.UOffsetT {
	builder.Prep(8, 96)
	builder.PrependUint64(reserved2)
	builder.PrependUint64(reserved1)
	builder.PrependUint64(extendedSize)
	builder.PrependUint64(extendedOffset)
	builder.PrependUint64(metadataSize)
	builder.PrependUint64(metadataOffset)
	builder.PrependUint64(indexSize)
	builder.PrependUint64(indexOffset)
	builder.PrependUint64(dataSize)
	builder.PrependUint64(dataOffset)
	builder.PrependUint64(uint64(version))
	builder.PrependUint64(uint64(signature))
	return builder.Offset()
}
