// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Header struct {
	_tab flatbuffers.Struct
}

func (rcv *Header) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Header) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Header) FileHeader(obj *FileHeader) *FileHeader {
	if obj == nil {
		obj = new(FileHeader)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+0)
	return obj
}
func (rcv *Header) IndexHeader(obj *IndexHeader) *IndexHeader {
	if obj == nil {
		obj = new(IndexHeader)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+96)
	return obj
}

func CreateHeader(builder *flatbuffers.Builder, file_header_signature HeaderSignature, file_header_version HeaderVersion, file_header_dataOffset uint64, file_header_dataSize uint64, file_header_indexOffset uint64, file_header_indexSize uint64, file_header_metadataOffset uint64, file_header_metadataSize uint64, file_header_extendedOffset uint64, file_header_extendedSize uint64, file_header_reserved1 uint64, file_header_reserved2 uint64, index_header_magic IndexMagic, index_header_format IndexFormat, index_header_maxZoom uint64, index_header_blockLevelsMask uint64, index_header_rootOffset uint64, index_header_rootSize uint64, index_header_reserved1 uint64, index_header_reserved2 uint64, index_header_reserved3 uint64, index_header_reserved4 uint64, index_header_reserved5 uint64, index_header_reserved6 uint64) flatbuffers.UOffsetT {
	builder.Prep(8, 192)
	builder.Prep(8, 96)
	builder.PrependUint64(index_header_reserved6)
	builder.PrependUint64(index_header_reserved5)
	builder.PrependUint64(index_header_reserved4)
	builder.PrependUint64(index_header_reserved3)
	builder.PrependUint64(index_header_reserved2)
	builder.PrependUint64(index_header_reserved1)
	builder.PrependUint64(index_header_rootSize)
	builder.PrependUint64(index_header_rootOffset)
	builder.PrependUint64(index_header_blockLevelsMask)
	builder.PrependUint64(index_header_maxZoom)
	builder.PrependUint64(uint64(index_header_format))
	builder.PrependUint64(uint64(index_header_magic))
	builder.Prep(8, 96)
	builder.PrependUint64(file_header_reserved2)
	builder.PrependUint64(file_header_reserved1)
	builder.PrependUint64(file_header_extendedSize)
	builder.PrependUint64(file_header_extendedOffset)
	builder.PrependUint64(file_header_metadataSize)
	builder.PrependUint64(file_header_metadataOffset)
	builder.PrependUint64(file_header_indexSize)
	builder.PrependUint64(file_header_indexOffset)
	builder.PrependUint64(file_header_dataSize)
	builder.PrependUint64(file_header_dataOffset)
	builder.PrependUint64(uint64(file_header_version))
	builder.PrependUint64(uint64(file_header_signature))
	return builder.Offset()
}
