// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type HeaderSignature uint64

const (
	HeaderSignatureInvalid HeaderSignature = 0
	HeaderSignatureValue   HeaderSignature = 91557097722967
)

var EnumNamesHeaderSignature = map[HeaderSignature]string{
	HeaderSignatureInvalid: "Invalid",
	HeaderSignatureValue:   "Value",
}

var EnumValuesHeaderSignature = map[string]HeaderSignature{
	"Invalid": HeaderSignatureInvalid,
	"Value":   HeaderSignatureValue,
}

func (v HeaderSignature) String() string {
	if s, ok := EnumNamesHeaderSignature[v]; ok {
		return s
	}
	return "HeaderSignature(" + strconv.FormatInt(int64(v), 10) + ")"
}
