// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type HeaderVersion uint64

const (
	HeaderVersionInvalid HeaderVersion = 0
	HeaderVersionV01     HeaderVersion = 1
	HeaderVersionV02     HeaderVersion = 2
)

var EnumNamesHeaderVersion = map[HeaderVersion]string{
	HeaderVersionInvalid: "Invalid",
	HeaderVersionV01:     "V01",
	HeaderVersionV02:     "V02",
}

var EnumValuesHeaderVersion = map[string]HeaderVersion{
	"Invalid": HeaderVersionInvalid,
	"V01":     HeaderVersionV01,
	"V02":     HeaderVersionV02,
}

func (v HeaderVersion) String() string {
	if s, ok := EnumNamesHeaderVersion[v]; ok {
		return s
	}
	return "HeaderVersion(" + strconv.FormatInt(int64(v), 10) + ")"
}
