// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type HeaderSize uint64

const (
	HeaderSizeRegular  HeaderSize = 192
	HeaderSizeExtended HeaderSize = 512
)

var EnumNamesHeaderSize = map[HeaderSize]string{
	HeaderSizeRegular:  "Regular",
	HeaderSizeExtended: "Extended",
}

var EnumValuesHeaderSize = map[string]HeaderSize{
	"Regular":  HeaderSizeRegular,
	"Extended": HeaderSizeExtended,
}

func (v HeaderSize) String() string {
	if s, ok := EnumNamesHeaderSize[v]; ok {
		return s
	}
	return "HeaderSize(" + strconv.FormatInt(int64(v), 10) + ")"
}
