// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type IndexFormat uint64

const (
	IndexFormatInvalid    IndexFormat = 0
	IndexFormatBasicPlain IndexFormat = 1
	IndexFormatPlain      IndexFormat = 2
	IndexFormatSparse     IndexFormat = 3
)

var EnumNamesIndexFormat = map[IndexFormat]string{
	IndexFormatInvalid:    "Invalid",
	IndexFormatBasicPlain: "BasicPlain",
	IndexFormatPlain:      "Plain",
	IndexFormatSparse:     "Sparse",
}

var EnumValuesIndexFormat = map[string]IndexFormat{
	"Invalid":    IndexFormatInvalid,
	"BasicPlain": IndexFormatBasicPlain,
	"Plain":      IndexFormatPlain,
	"Sparse":     IndexFormatSparse,
}

func (v IndexFormat) String() string {
	if s, ok := EnumNamesIndexFormat[v]; ok {
		return s
	}
	return "IndexFormat(" + strconv.FormatInt(int64(v), 10) + ")"
}
