// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type IndexHeader struct {
	_tab flatbuffers.Struct
}

func (rcv *IndexHeader) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *IndexHeader) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *IndexHeader) Magic() IndexMagic {
	return IndexMagic(rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(0)))
}
func (rcv *IndexHeader) MutateMagic(n IndexMagic) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(0), uint64(n))
}

func (rcv *IndexHeader) Format() IndexFormat {
	return IndexFormat(rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(8)))
}
func (rcv *IndexHeader) MutateFormat(n IndexFormat) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(8), uint64(n))
}

func (rcv *IndexHeader) MaxZoom() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(16))
}
func (rcv *IndexHeader) MutateMaxZoom(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(16), n)
}

func (rcv *IndexHeader) BlockLevelsMask() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(24))
}
func (rcv *IndexHeader) MutateBlockLevelsMask(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(24), n)
}

func (rcv *IndexHeader) RootOffset() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(32))
}
func (rcv *IndexHeader) MutateRootOffset(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(32), n)
}

func (rcv *IndexHeader) RootSize() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(40))
}
func (rcv *IndexHeader) MutateRootSize(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(40), n)
}

func (rcv *IndexHeader) Reserved1() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(48))
}
func (rcv *IndexHeader) MutateReserved1(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(48), n)
}

func (rcv *IndexHeader) Reserved2() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(56))
}
func (rcv *IndexHeader) MutateReserved2(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(56), n)
}

func (rcv *IndexHeader) Reserved3() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(64))
}
func (rcv *IndexHeader) MutateReserved3(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(64), n)
}

func (rcv *IndexHeader) Reserved4() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(72))
}
func (rcv *IndexHeader) MutateReserved4(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(72), n)
}

func (rcv *IndexHeader) Reserved5() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(80))
}
func (rcv *IndexHeader) MutateReserved5(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(80), n)
}

func (rcv *IndexHeader) Reserved6() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(88))
}
func (rcv *IndexHeader) MutateReserved6(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(88), n)
}

func CreateIndexHeader(builder *flatbuffers.Builder, magic IndexMagic, format IndexFormat, maxZoom uint64, blockLevelsMask uint64, rootOffset uint64, rootSize uint64, reserved1 uint64, reserved2 uint64, reserved3 uint64, reserved4 uint64, reserved5 uint64, reserved6 uint64) flatbuffers.UOffsetT {
	builder.Prep(8, 96)
	builder.PrependUint64(reserved6)
	builder.PrependUint64(reserved5)
	builder.PrependUint64(reserved4)
	builder.PrependUint64(reserved3)
	builder.PrependUint64(reserved2)
	builder.PrependUint64(reserved1)
	builder.PrependUint64(rootSize)
	builder.PrependUint64(rootOffset)
	builder.PrependUint64(blockLevelsMask)
	builder.PrependUint64(maxZoom)
	builder.PrependUint64(uint64(format))
	builder.PrependUint64(uint64(magic))
	return builder.Offset()
}
