// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type IndexMagic uint64

const (
	IndexMagicInvalid IndexMagic = 0
	IndexMagicValue   IndexMagic = 1481200727
)

var EnumNamesIndexMagic = map[IndexMagic]string{
	IndexMagicInvalid: "Invalid",
	IndexMagicValue:   "Value",
}

var EnumValuesIndexMagic = map[string]IndexMagic{
	"Invalid": IndexMagicInvalid,
	"Value":   IndexMagicValue,
}

func (v IndexMagic) String() string {
	if s, ok := EnumNamesIndexMagic[v]; ok {
		return s
	}
	return "IndexMagic(" + strconv.FormatInt(int64(v), 10) + ")"
}
