// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LinkItem struct {
	_tab flatbuffers.Struct
}

func (rcv *LinkItem) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LinkItem) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *LinkItem) TileCode() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *LinkItem) MutateTileCode(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *LinkItem) LinkCode() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *LinkItem) MutateLinkCode(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func CreateLinkItem(builder *flatbuffers.Builder, tileCode uint32, linkCode uint32) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.PrependUint32(linkCode)
	builder.PrependUint32(tileCode)
	return builder.Offset()
}
