// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LocationItem struct {
	_tab flatbuffers.Struct
}

func (rcv *LocationItem) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LocationItem) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *LocationItem) TileCode() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *LocationItem) MutateTileCode(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *LocationItem) Location(obj *Location) *Location {
	if obj == nil {
		obj = new(Location)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+4)
	return obj
}

func CreateLocationItem(builder *flatbuffers.Builder, tileCode uint32, location_v0 uint32, location_v1 uint32) flatbuffers.UOffsetT {
	builder.Prep(4, 12)
	builder.Prep(4, 8)
	builder.PrependUint32(location_v1)
	builder.PrependUint32(location_v0)
	builder.PrependUint32(tileCode)
	return builder.Offset()
}
