// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ResponseParams struct {
	_tab flatbuffers.Table
}

func GetRootAsResponseParams(buf []byte, offset flatbuffers.UOffsetT) *ResponseParams {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ResponseParams{}
	x.Init(buf, n+offset)
	return x
}

func FinishResponseParamsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsResponseParams(buf []byte, offset flatbuffers.UOffsetT) *ResponseParams {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ResponseParams{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedResponseParamsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ResponseParams) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ResponseParams) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ResponseParams) ContentType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ResponseParams) ContentEncoding() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ResponseParamsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ResponseParamsAddContentType(builder *flatbuffers.Builder, contentType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(contentType), 0)
}
func ResponseParamsAddContentEncoding(builder *flatbuffers.Builder, contentEncoding flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(contentEncoding), 0)
}
func ResponseParamsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
