// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SparseBlock struct {
	_tab flatbuffers.Table
}

func GetRootAsSparseBlock(buf []byte, offset flatbuffers.UOffsetT) *SparseBlock {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SparseBlock{}
	x.Init(buf, n+offset)
	return x
}

func FinishSparseBlockBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSparseBlock(buf []byte, offset flatbuffers.UOffsetT) *SparseBlock {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SparseBlock{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSparseBlockBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SparseBlock) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SparseBlock) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SparseBlock) BlockType() BlockType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return BlockType(rcv._tab.GetUint32(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *SparseBlock) MutateBlockType(n BlockType) bool {
	return rcv._tab.MutateUint32Slot(4, uint32(n))
}

func (rcv *SparseBlock) DenseLocations(obj *DenseLocations, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SparseBlock) DenseLocationsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SparseBlock) SparseLocations(obj *SparseLocations, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SparseBlock) SparseLocationsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func SparseBlockStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func SparseBlockAddBlockType(builder *flatbuffers.Builder, blockType BlockType) {
	builder.PrependUint32Slot(0, uint32(blockType), 0)
}
func SparseBlockAddDenseLocations(builder *flatbuffers.Builder, denseLocations flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(denseLocations), 0)
}
func SparseBlockStartDenseLocationsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SparseBlockAddSparseLocations(builder *flatbuffers.Builder, sparseLocations flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(sparseLocations), 0)
}
func SparseBlockStartSparseLocationsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SparseBlockEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
